/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "filter.h"
#include <pthread.h>
char host1[15]="192.168.1.";
char host2[15]="192.168.1.";
char host3[15]="192.168.1.";
char host4[15]="192.168.1.";

CLIENT *clnt1;
CLIENT *clnt2;
CLIENT *clnt3;
CLIENT *clnt4;

char *leer_original_1_arg;
char *escribir_output_1_arg;




void* hilo(void* arg){
	int value = *(int*) arg;
	printf("Ejecutando hilo %d\n",value);

	// filtrar mi propio archivo pgm


	switch (value)
	{
	case 1:
		if (filtrar_imagen_1(&value, clnt1) == (void *) NULL) {
			clnt_perror (clnt1, "invocation failed");
		}
		break;
	case 2:
		if (filtrar_imagen_1(&value, clnt2) == (void *) NULL) {
			clnt_perror (clnt2, "invocation failed");
		}
		break;
	case 3:

		if (filtrar_imagen_1(&value, clnt3) == (void *) NULL) {
			clnt_perror (clnt3, "invocation failed");
		}
		break;
	case 4:
		if (filtrar_imagen_1(&value, clnt4) == (void *) NULL) {
			clnt_perror (clnt4, "invocation failed");
		}
		break;
	default:
	
		break;
	}



	


	pthread_exit(NULL);
}


void
filter_1(char *host)
{
	CLIENT *clnt;
	void  *result_1;
	char *leer_original_1_arg;
	void  *result_2;
	int  filtrar_imagen_1_arg;
	void  *result_3;
	char *escribir_output_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, FILTER, FV1, "tcp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = leer_original_1((void*)&leer_original_1_arg, clnt);
	if (result_1 == (void *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = filtrar_imagen_1(&filtrar_imagen_1_arg, clnt);
	if (result_2 == (void *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_3 = escribir_output_1((void*)&escribir_output_1_arg, clnt);
	if (result_3 == (void *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	if (argc < 5) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}

	strcat(host1,argv[1]);
	strcat(host2,argv[2]);
	strcat(host3,argv[3]);
	strcat(host4,argv[4]);
	pthread_t h1, h2, h3,h4;
	int a=1, b=2,c=3,d=4;



	clnt1 = clnt_create (host1, FILTER, FV1, "tcp");
	if (clnt1 == NULL) {
		clnt_pcreateerror (host1);
		exit (1);
	}
	clnt2 = clnt_create (host2, FILTER, FV1, "tcp");
	if (clnt2 == NULL) {
		clnt_pcreateerror (host2);
		exit (1);
	}
	clnt3 = clnt_create (host3, FILTER, FV1, "tcp");
	if (clnt3 == NULL) {
		clnt_pcreateerror (host3);
		exit (1);
	}
	clnt4 = clnt_create (host4, FILTER, FV1, "tcp");
	if (clnt4 == NULL) {
		clnt_pcreateerror (host4);
		exit (1);
	}


	//cargamos datos remotamente
	
	if (leer_original_1((void*)&leer_original_1_arg, clnt1) == (void *) NULL) {
		clnt_perror (clnt1, "cargar 1 failed");
	}
	if (leer_original_1((void*)&leer_original_1_arg, clnt2) == (void *) NULL) {
		clnt_perror (clnt2, "cargar 2 failed");
	}
	if (leer_original_1((void*)&leer_original_1_arg, clnt3) == (void *) NULL) {
		clnt_perror (clnt3, "cargar 3 failed");
	}
	if (leer_original_1((void*)&leer_original_1_arg, clnt4) == (void *) NULL) {
		clnt_perror (clnt4, "cargar 4 failed");
	}


	//Tomamos tiempo
	struct timeval inicio, fin;
    double tiempo;
    gettimeofday(&inicio, NULL);
    
	//lanzar 4 hilos donde se conecta a 1 server y ejecuta el filtrado

	if(pthread_create(&h1, NULL, hilo, (void*)&a)!=0){
		printf("\nError al crear el hilo");
		return 1;
	}
	if(pthread_create(&h2, NULL, hilo, (void*)&b)!=0){
		printf("\nError al crear el hilo");
		return 1;
	}
	if(pthread_create(&h3, NULL, hilo, (void*)&c)!=0){
		printf("\nError al crear el hilo");
		return 1;
	}
	if(pthread_create(&h4, NULL, hilo, (void*)&d)!=0){
		printf("\nError al crear el hilo");
		return 1;
	}


	//esperamos con join
	pthread_join(h1,NULL);
	pthread_join(h2,NULL);
	pthread_join(h3,NULL);
	pthread_join(h4,NULL);

	//Tomamos tiempo
	gettimeofday(&fin, NULL);
    tiempo = (double)(fin.tv_sec - inicio.tv_sec) + (double)(fin.tv_usec-inicio.tv_usec)/1000000.0;

	//imprimimos tiempo
    printf("\nParalelo Tardo: %.6f segundos\n",tiempo);


	//guardamos cambios remotamente

	if (escribir_output_1((void*)&escribir_output_1_arg, clnt1) == (void *) NULL) {
		clnt_perror (clnt1, "save 1 failed");
	}
	if (escribir_output_1((void*)&escribir_output_1_arg, clnt2) == (void *) NULL) {
		clnt_perror (clnt2, "save 2 failed");
	}
	if (escribir_output_1((void*)&escribir_output_1_arg, clnt3) == (void *) NULL) {
		clnt_perror (clnt3, "save 3 failed");
	}
	if (escribir_output_1((void*)&escribir_output_1_arg, clnt4) == (void *) NULL) {
		clnt_perror (clnt4, "save 4 failed");
	}

	//cerramos conexiones
	clnt_destroy (clnt1);
	clnt_destroy (clnt2);
	clnt_destroy (clnt3);
	clnt_destroy (clnt4);


	exit (0);
}
